[package]
name = "aoc-rust-2018"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10"
chrono = "0.4"
num = "0.4"
itertools = "0.12"
strum = "0.26"
strum_macros = "0.26"
